### ISSUE TITLE
Iron End Ore Does Not Exist

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/elementary-ores#13]
Minecraft Version: 1.18.2

Forge Version: 40.1.60

Mod Version: 1.1.0

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

Hey Loth!

Looks like End Iron isn't in the mod currently. I just wanted to make sure it was intended.

Thanks!

**Comment by Lothrazar** [comment]
i left out nether-redstone and iron-end on purpose, since they are mid tier ores already very common in other dimensions, plus the color makes them almost invisible (white iron on endstone, redstone on red netherrack).  

Ill look into adding them maybe with just the worldgen defaults to zero so that way the features and block are still registered. the ghast ore was part of another plan to add mobdrop ores to the mod in the same way, so blaze or gunpowder ore might show up at some point later

**Comment by Lothrazar** [comment]
Ive added ore_redstone_nether and ore_iron_end with worldgen configs, its coming out today. mod  will depend on new library i made https://www.curseforge.com/minecraft/mc-mods/flib (similar to placebo) which is the same lib scraps will use and some new mods im working on

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/elementary-ores/files/3956498
